apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: sock-shop
data:
  alertmanager.yml: |
    
    global:
      resolve_timeout: 5m

    receivers:
      - name: 'email'
        email_configs:
          - to: 'florenceokoli91@gmail.com'
            send_resolved: true

    route:
      group_by: ['alertname']
      receiver: 'email'
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'email'
