apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: sock-shop
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.37.0
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              subPath: prometheus.yml
      volumes:
        - name: config
          configMap:
            name: prometheus-config
