apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sock-shop
data:
  prometheus.yml: |
    # Insert the contents of your prometheus.yml here
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'node'
        static_configs:
          - targets: ['node-exporter:9100']
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - 'alertmanager.sock-shop.svc.cluster.local:9093'
    
    rule_files:
      - 'alerting-rules.yml'
